USE iERP_AQMR_PR
GO

DECLARE @DocumentNumber NVARCHAR(50) = '2024-02-9071-7495-000000000000015' -- NUMERO DE DOC ESPECIFICO QUE QUIERO BUSCAR
DECLARE @SQL NVARCHAR(MAX) = ''

-- Generar el script dinámico para buscar en todas las tablas y columnas
SELECT @SQL = @SQL + 'SELECT ''' + TABLE_SCHEMA + '.' + TABLE_NAME + ''' AS TableName, ''' + COLUMN_NAME + ''' AS ColumnName, ' + COLUMN_NAME + ' AS DocumentNumber FROM ' + TABLE_SCHEMA + '.' + TABLE_NAME + ' WHERE ' + COLUMN_NAME + ' = ''' + @DocumentNumber + ''' UNION ALL '
FROM INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE IN ('char', 'varchar', 'nchar', 'nvarchar') -- PONER AQUI EL TIPO DE DATO QUE QUIERO QUE BUSQUE

-- Eliminar el último 'UNION ALL'
SET @SQL = LEFT(@SQL, LEN(@SQL) - 10)

-- Ejecutar el script dinámico
EXEC sp_executesql @SQL

-- ESPECIFICIAR SIEMPRE QUE BASE DE DATOS QUIERO USAR PARA QUE NO BUSQUE EN TODAS LAS BASES DE DATOS QUE TENGO GUARDADAS
-- USAR ESTE SCRIPT PARA CONSULTAS MUY MUY ESPECIFICAS 
-- TARDA MINIMO 15 MIN CON BASE DE DATOS IERP CONFREMARCA